name: suchi
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.4.0
  provider: ^6.1.2
  badges: ^3.1.2
  ionicons: ^0.2.2
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  file_picker: ^8.3.1
  cloudinary_public: ^0.23.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/bgHome.jpg
    - images/bgProduct.jpg
    - images/splash.jpg
    - images/logo.png
    - images/proIcon.png
    - images/proIcon2.png
    - images/bagShopping.png
    - images/coin.png
    - images/male.jpg
    - images/female.jpg
    - images/sun.jpg
    - images/special.jpg
    - images/c1.jpg
    - images/c2.jpg
    - images/c3.jpg
    - images/c4.jpg
    - images/a1.png
    - images/a2.jpg
    - images/a3.png
    - images/a4.png
    - images/f1.png
    - images/f2.png
    - images/f3.png
    - images/marvel.png
    - images/tom.png
    - images/naru.png
    - images/payment.jpg
    - images/shipping.jpg
    - images/genuin.jpg
    - images/bengali.jpg

